project:
  type: website

website:
  title: "Ignacio Bonmati Gonzalvez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.ipynb
        text: Early Warning System Analysis
    right:
      - href: resume.qmd
        text: Resume
      - href: cover_letter.qmd
        text: Cover Letter

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true